In [1]:
!pip install rake-nltk

  Created wheel for rake-nltk: filename=rake_nltk-1.0.4-py2.py3-none-any.whl size=7819 sha256=4a46e470e12cee2873795b718982c31614cf27d9f264f47a715478c659e180e0
  Stored in directory: /root/.cache/pip/wheels/ef/92/fc/271b3709e71a96ffe934b27818946b795ac6b9b8ff8682483f
Successfully built rake-nltk


In [2]:
import pandas as pd
import numpy as np
from rake_nltk import Rake

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# Dataset contains top 250 top rated movies from IMDB
df = pd.read_csv('https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7')

In [4]:
df.head()

Unnamed: 0  ... Response
0           1  ...     True
1           2  ...     True
2           3  ...     True
3           4  ...     True
4           5  ...     True

[5 rows x 38 columns]

In [5]:
# Only keep important factors for recommending movies, such as
# Title, Genre, Director, Actors and Plot
df = df[['Title','Genre','Director','Actors','Plot']]

In [6]:
df.head()

Title  ...                                               Plot
0  The Shawshank Redemption  ...  Two imprisoned men bond over a number of years...
1             The Godfather  ...  The aging patriarch of an organized crime dyna...
2    The Godfather: Part II  ...  The early life and career of Vito Corleone in ...
3           The Dark Knight  ...  When the menace known as the Joker emerges fro...
4              12 Angry Men  ...  A jury holdout attempts to prevent a miscarria...

[5 rows x 5 columns]

In [7]:
# A library called Rake, that extracts keywords from a text
# Hence, I am going to extract keywords from the Plot column; so that I 
# only consider the most relevant keywords in the plot description

df['Plot Key Words'] = ""

for index, row in df.iterrows():
  plot = row['Plot']

  rake = Rake()

  rake.extract_keywords_from_text(plot)

  keywords_dict_score = rake.get_word_degrees()

  row["Plot Key Words"] = list(keywords_dict_score.keys())

df.drop(columns=["Plot"], inplace=True)

In [9]:
df.head(20)

Title  ...                                     Plot Key Words
0                            The Shawshank Redemption  ...  [years, two, imprisoned, men, bond, finding, s...
1                                       The Godfather  ...  [aging, patriarch, organized, crime, dynasty, ...
2                              The Godfather: Part II  ...  [career, vito, corleone, 1920s, new, york, ear...
3                                     The Dark Knight  ...  [mysterious, past, physical, tests, menace, kn...
4                                        12 Angry Men  ...  [justice, forcing, evidence, reconsider, misca...
5                                    Schindler's List  ...  [jewish, workforce, witnessing, occupied, pola...
6       The Lord of the Rings: The Return of the King  ...  [men, one, ring, army, sam, draw, world, ganda...
7                                        Pulp Fiction  ...  [four, tales, lives, redemption, boxer, two, m...
8                                          Fight Club  ...  [crosses, paths, insomniac, office, worker, wa...
9   The Lord of the Rings: The Fellowship of the Ring  ...  [shire, journey, save, middle, earth, destroy,...
10                                       Forrest Gump  ...  [forrest, gump, intelligent, eludes, accidenta...
11     Star Wars: Episode V - The Empire Strikes Back  ...  [rebels, newly, established, base, capture, lu...
12                                          Inception  ...  [use, thief, given, dream, steals, corporate, ...
13              The Lord of the Rings: The Two Towers  ...  [divided, fellowship, makes, sam, edge, closer...
14                    One Flew Over the Cuckoo's Nest  ...  [rallies, scared, patients, trouble, getting, ...
15                                         Goodfellas  ...  [story, years, covering, mob, partners, jimmy,...
16                                         The Matrix  ...  [role, war, reality, true, nature, mysterious,...
17                 Star Wars: Episode IV - A New Hope  ...  [galaxy, rescue, princess, leia, evil, darth, ...
18                                              Se7en  ...  [hunt, seven, deadly, sins, serial, killer, ve...
19                              It's a Wonderful Life  ...  [heaven, desperately, frustrated, businessman,...

[20 rows x 5 columns]

In [10]:
for index, row in df.iterrows():
  # putting the genres in a list
  row["Genre"] = list(row["Genre"].lower().split(','))

  # Name of Director(s) to lowercase, and remove whitespace, and put into a list
  row['Director'] = row["Director"].lower().replace(' ','').split(',')

  # Name of Actors(s) to lowercase, and remove whitespace, and put into a list
  row["Actors"] = list(row["Actors"].lower().replace(' ','').split(','))

In [11]:
df.head()

Title  ...                                     Plot Key Words
0  The Shawshank Redemption  ...  [years, two, imprisoned, men, bond, finding, s...
1             The Godfather  ...  [aging, patriarch, organized, crime, dynasty, ...
2    The Godfather: Part II  ...  [career, vito, corleone, 1920s, new, york, ear...
3           The Dark Knight  ...  [mysterious, past, physical, tests, menace, kn...
4              12 Angry Men  ...  [justice, forcing, evidence, reconsider, misca...

[5 rows x 5 columns]

In [12]:
df['Bag of Words'] = ""
columns = df.columns

for index, row in df.iterrows():
  words = ''
  for col in columns:
    if col == 'Title':
      continue
    else:
      seperator = ' '
      words = words + seperator.join(row[col]) + ' '

  # Remove the last whitespace character
  row['Bag of Words'] = words[:-1]

df.drop(columns=["Genre", "Director", "Actors", "Plot Key Words"], inplace = True)

In [14]:
df.head(20)

Title                                       Bag of Words
0                            The Shawshank Redemption  crime  drama frankdarabont timrobbins morganfr...
1                                       The Godfather  crime  drama francisfordcoppola marlonbrando a...
2                              The Godfather: Part II  crime  drama francisfordcoppola alpacino rober...
3                                     The Dark Knight  action  crime  drama christophernolan christia...
4                                        12 Angry Men  crime  drama sidneylumet martinbalsam johnfied...
5                                    Schindler's List  biography  drama  history stevenspielberg liam...
6       The Lord of the Rings: The Return of the King  adventure  drama  fantasy peterjackson noelapp...
7                                        Pulp Fiction  crime  drama quentintarantino timroth amandapl...
8                                          Fight Club  drama davidfincher edwardnorton bradpitt meatl...
9   The Lord of the Rings: The Fellowship of the Ring  adventure  drama  fantasy peterjackson alanhow...
10                                       Forrest Gump  comedy  drama  romance robertzemeckis tomhanks...
11     Star Wars: Episode V - The Empire Strikes Back  action  adventure  fantasy irvinkershner markh...
12                                          Inception  action  adventure  sci-fi christophernolan leo...
13              The Lord of the Rings: The Two Towers  adventure  drama  fantasy peterjackson bruceal...
14                    One Flew Over the Cuckoo's Nest  drama milosforman michaelberryman peterbrocco ...
15                                         Goodfellas  crime  drama martinscorsese robertdeniro rayli...
16                                         The Matrix  action  sci-fi lanawachowski lillywachowski ke...
17                 Star Wars: Episode IV - A New Hope  action  adventure  fantasy georgelucas markham...
18                                              Se7en  crime  drama  mystery davidfincher morganfreem...
19                              It's a Wonderful Life  drama  family  fantasy frankcapra jamesstewart...

In [15]:
vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform(df['Bag of Words'])

In [16]:
# get the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [17]:
print(cosine_sim)

[[1.         0.14638501 0.1315587  ... 0.05       0.05       0.05270463]
 [0.14638501 1.         0.34236839 ... 0.048795   0.048795   0.05143445]
 [0.1315587  0.34236839 1.         ... 0.0438529  0.0438529  0.04622502]
 ...
 [0.05       0.048795   0.0438529  ... 1.         0.05       0.05270463]
 [0.05       0.048795   0.0438529  ... 0.05       1.         0.05270463]
 [0.05270463 0.05143445 0.04622502 ... 0.05270463 0.05270463 1.        ]]


In [18]:
indices = pd.Series(df["Title"])
ind = indices
ind[:5]

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [19]:
def recommendations(title):
  recommended_movies = []

  # Retrieves the index of the movie in the dataset
  idx = indices[indices == title].index[0]

  # Retrieves all the scores from the cosine similarity matrix,
  # convert to a pd.Series, and sort the scores in descending order
  score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
  
  # Retrieves the highest 10 scores, excluding its own movie
  top_10_indexes = list(score_series.iloc[1:11].index)

  for i in top_10_indexes:
    recommended_movies.append(list(df["Title"])[i])

  return recommended_movies

In [21]:
recommendations('Inception')

['Mad Max: Fury Road',
 'Interstellar',
 'The Dark Knight Rises',
 'Guardians of the Galaxy',
 'Aliens',
 'Guardians of the Galaxy Vol. 2',
 'Spider-Man: Homecoming',
 'The Prestige',
 'The Matrix',
 'The Revenant']